name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: recent
            asset_name: recent-linux-amd64.tar.gz
          - os: macos-latest
            artifact_name: recent
            asset_name: recent-macos-amd64.tar.gz

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Create tar.gz archive
        run: |
          mkdir -p dist
          cp target/release/${{ matrix.artifact_name }} dist/
          cd dist
          tar -czf ${{ matrix.asset_name }} ${{ matrix.artifact_name }}
          cd ..

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true

  update-homebrew:
    name: Update Homebrew Formula
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Extract version
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create and update Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v2
        with:
          formula-name: grec
          formula-path: Formula/grec.rb
          homebrew-tap: ${{ github.repository_owner }}/homebrew-zapfhahn
          base-branch: main
          download-url: https://github.com/${{ github.repository }}/releases/download/v${{ steps.extract_version.outputs.VERSION }}/recent-macos-amd64.tar.gz
          commit-message: |
            {{formulaName}} {{version}}
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
